### ISSUE TITLE
Is HTTP'S and gRPC supported by edgemesh??? 

### ISSUE THREAD

**Issue by abhinavjha126** [kubeedge/edgemesh#329]
Hi i am using KubeEdge v1. 8.1.
On top of that i am using Edgemesh. Please tell whether this setup supports HTTPS and gRPC??

**Comment by Poorunga** [comment]
Yes. Because edgemesh supports tcp, and https and grpc are based on tcp, so edgemesh can support them.

**Comment by abhinavjha126** [comment]
@Poorunga Can you please share the file or configurations which we can edit/add to enable gRPC protocol.gRPC is important for our application,please help me in enabling it.

**Comment by Poorunga** [comment]
1. create your grpc-app-deploment.yaml
2. create your grpc grpc-app-service.yaml, server.yaml may like:
```
kind: Service
apiVersion: v1
metadata:
  name: your-grpc-app-svc
spec:
  selector:
    app: your-grpc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
```
3. create them
```
$ kubectl apply -f grpc-app-deploment.yaml
$ kubectl apply -f grpc-app-service.yaml
```
4. Now, you can access it by grpc-app-service's clusterIP or domain name.
5. Done!
