### ISSUE TITLE
edge node cannot access the service with clusterip

### ISSUE THREAD

**Issue by seven-07-11** [kubeedge/edgemesh#338]
kubernetes1.20
kubeedge1.8.2
edgemesh:last 
kube-proxy and coredns not scheduling in edge node，edgemesh deployment successful

I can't access services through podip or service

**Comment by seven-07-11** [comment]
Can cloud services be accessed from edge nodes？How to configure it? How to configure? Is there a correct configuration tutorial

**Comment by seven-07-11** [comment]
![M%G5 MGHVNCMD(Q}UWAILTB](https://user-images.githubusercontent.com/62531302/162135698-2179082f-b219-469a-8fc6-17c45ac274b7.png) edgemesh-server log
![592IC25504XMC0_~G $PCNF](https://user-images.githubusercontent.com/62531302/162135837-bb452a4c-3e5a-4a6f-955c-cc2fb9b64cdb.png)cloudcore log
![image](https://user-images.githubusercontent.com/62531302/162136039-2aaf2632-42b7-4f4e-b01c-8eb6a8b05c0a.png)edgecore log
![image](https://user-images.githubusercontent.com/62531302/162136178-04ed989c-7be8-4a35-ae2b-dd650c9ca321.png)edgecore log

**Comment by Poorunga** [comment]
need some edgemesh-agent log

**Comment by Poorunga** [comment]
> I can't access services through podip or service

edgemesh only support access services by clusterip or services DNS name.

**Comment by seven-07-11** [comment]
> > I can't access services through podip or service
> 
> edgemesh only support access services by clusterip or services DNS name.

Sorry for my late reply, I access service through clusterip, but there was no response. There was no problem accessing in the cloud node
![image](https://user-images.githubusercontent.com/62531302/162166449-fe9bdd0e-6676-47aa-ba29-e5c9aa1883bf.png)

**edgemesh-agent-master log**
![3~T5Y5}BOXB)$ )X@@Q}3DR](https://user-images.githubusercontent.com/62531302/162183143-f4464488-189f-4726-8b65-78133a306feb.png)

**edgemesh-server log**

**edgemesh-agent-slaver**
![F9PRCJ$KBPKHO6D4{)5BT`5](https://user-images.githubusercontent.com/62531302/162183894-43e61d95-5021-4a3d-b1e3-2e030de3308a.png)

**edgemesh-agent-edge log**
![image](https://user-images.githubusercontent.com/62531302/162184265-5f2fc9a0-eb41-4fd6-a624-1dbee0f522cb.png)

**Comment by seven-07-11** [comment]
I use binary to deploy kubeedge,
Using helm to deploy edgemesh, the configuration of edgemesh has not been modified after successful deployment. Do I need to modify it?Or Kube proxy and coredns?
![%Z(QOGD2Q4IJ(U4FA7(UNFF](https://user-images.githubusercontent.com/62531302/162185289-daad44ed-d52d-4d89-b7dc-4b4f12e00d5b.png)

**Comment by seven-07-11** [comment]
I also found a problem. When deleting the service endpoint, I can access the service through clusterip: curl (52) empty reply from server
However, when the endpoint exists, I can access the service directly through podid, but I cannot access the service through clusterip
![image](https://user-images.githubusercontent.com/62531302/162188188-063ae0c2-bab9-45d4-bc64-d874205385ad.png)

**Comment by seven-07-11** [comment]
I also found a problem. When deleting the service endpoint, I can access the service through clusterip: curl (52) empty reply from server
However, when the endpoint exists, I can access the service directly through podid, but I cannot access the service through clusterip
![image](https://user-images.githubusercontent.com/62531302/162188188-063ae0c2-bab9-45d4-bc64-d874205385ad.png)

**Comment by Poorunga** [comment]
The service whose cluster ip is 10.96.0.1 is a very special service. This is a service automatically created by k8s to access the kube apiserver. It is also an external service, and if you want to access it at the edge, some additional configuration is required.

**Comment by Poorunga** [comment]
Let's start with some simple services, you can refer to edgemesh's test case: https://edgemesh.netlify.app/guide/test-case.html

**Comment by seven-07-11** [comment]
> The service whose cluster ip is 10.96.0.1 is a very special service. This is a service automatically created by k8s to access the kube apiserver. It is also an external service, and if you want to access it at the edge, some additional configuration is required.

I deployed the joint inference service of Sedna. Edge needs to access port 5000 of cloud, but it cannot be accessed through clusterip. DNS resolution is normal
In the service test case, I deployed TCP test, and the service endpoint was deployed on edge node
The pod in edge can be accessed, but the pod in cloud cannot

And cross-edge-cloud test failed, and no other services were tested. It is certain that there is a problem with Edge and cloud communication. Can you infer the cause of the problem？

**Comment by Poorunga** [comment]
This is a k8s knowledge, if your pod is a host network, you need to configure dnsPolicy like `dnsPolicy: ClusterFirstWithHostNet `, Please refer to kubernetes docs: https://kubernetes.io/zh/docs/concepts/services-networking/dns-pod-service/#pod-s-dns -policy

And how to fix your problem:
```
CLOUD_NODE="cloud-node-name"
EDGE_NODE="edge-node-name"


kubectl create -f - <<EOF
apiVersion: sedna.io/v1alpha1
kind: JointInferenceService
metadata:
  name: helmet-detection-inference-example
  namespace: default
spec:
  edgeWorker:
    model:
      name: "helmet-detection-inference-little-model"
    hardExampleMining:
      name: "IBT"
      parameters:
        - key: "threshold_img"
          value: "0.9"
        - key: "threshold_box"
          value: "0.9"
    template:
      spec:
        nodeName: $EDGE_NODE
        dnsPolicy: ClusterFirstWithHostNet       <----------- look at here!!!
        containers:
        - image: kubeedge/sedna-example-joint-inference-helmet-detection-little:v0.3.0
          imagePullPolicy: IfNotPresent
          name:  little-model
          env:  # user defined environments
          - name: input_shape
            value: "416,736"
          - name: "video_url"
            value: "rtsp://localhost/video"
          - name: "all_examples_inference_output"
            value: "/data/output"
          - name: "hard_example_cloud_inference_output"
            value: "/data/hard_example_cloud_inference_output"
          - name: "hard_example_edge_inference_output"
            value: "/data/hard_example_edge_inference_output"
          resources:  # user defined resources
            requests:
              memory: 64M
              cpu: 100m
            limits:
              memory: 2Gi
          volumeMounts:
            - name: outputdir
              mountPath: /data/
        volumes:   # user defined volumes
          - name: outputdir
            hostPath:
              # user must create the directory in host
              path: /joint_inference/output
              type: Directory

  cloudWorker:
    model:
      name: "helmet-detection-inference-big-model"
    template:
      spec:
        nodeName: $CLOUD_NODE
        containers:
          - image: kubeedge/sedna-example-joint-inference-helmet-detection-big:v0.3.0
            name:  big-model
            imagePullPolicy: IfNotPresent
            env:  # user defined environments
              - name: "input_shape"
                value: "544,544"
            resources:  # user defined resources
              requests:
                memory: 2Gi
EOF
```
