### ISSUE TITLE
Regarding accessing of HTTP and HTTPS Gateway simultaneously!! 

### ISSUE THREAD

**Issue by abhinavjha126** [kubeedge/edgemesh#346]
I am using Kubeedge version v1. 8.1.I am not able to add HTTP and HTTPS Gateway access together. What should I do??????

**Comment by Poorunga** [comment]
If you don't provide some environment information, some yaml files of gateway,virtualservice, logs, etc, I won't be able to see any problem.

**Comment by abhinavjha126** [comment]
@Poorunga This is my VIRTUAL SERVICE File

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: edgemesh-gateway-svc
  namespace: zbl
spec:
  gateways:
  - edgemesh-gateway
  hosts:
  - '*.web.com'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx-custom
        port:
          number: 80

Please tell how can i add one more VIRTUAL SERVICE along with this.It is not accepting 2 VIRTUAL SERVICE.
Will i have to make 2 different file or one file is sufficient for VIRTUAL SERVICE????

**Comment by Poorunga** [comment]
EdgeMesh only support one HttpRoute match now.

**Comment by sdghchj** [comment]
A virtual service can only configure a single TCP service.

**Comment by abhinavjha126** [comment]
@Poorunga @sdghchj Can u please provide VirtualService for tcp protocol

**Comment by abhinavjha126** [comment]
> A virtual service can only configure a single TCP service.

Can u please send the virtualservice file

**Comment by sdghchj** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: edgemesh-gateway
spec:
  selector:
    kubeedge: edgemesh-gateway
  servers:
    - hosts:
        - '*'
      port:
        name: tcp-1
        number: 80
        protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: edgemesh-gateway-svc
spec:
  gateways:
    - edgemesh-gateway
  hosts:
    - '*'
  tcp:
    - route:
      - destination:
          host: xxxxxx-svc
          port:
            number: 8080
```
