### ISSUE TITLE
Hardcoded edgemesh-server port

### ISSUE THREAD

**Issue by vcozzolino** [kubeedge/edgemesh#49]
**What happened**:
Changing the port of the edgemesh-server in the YAML file does not affect the port on which the pod will listen to. It will always listen on port `10004` because it's hardcoded -> [check here](https://github.com/kubeedge/edgemesh/blob/966f3b02fe10e5a615a834a76c7982e44c9ed1c2/server/cmd/edgemesh-server/app/config/config.go#L70).
 
**What you expected to happen**:
Changing the port in the YAML file should affect the port on which edgemesh-server is deployed.

**How to reproduce it (as minimally and precisely as possible)**:
Change the port in the deployment YAML file.

**Comment by ZBoIsHere** [comment]
@vcozzolino hi, bro, it's not hardcoded, it's default value, you can defined another value in edgemesh-server configmap

**Comment by ZBoIsHere** [comment]
![image](https://user-images.githubusercontent.com/44860970/130211215-1cab2cdd-217e-4707-b78e-6dc38473c8ce.png)
like that

**Comment by vcozzolino** [comment]
You are right. I thought that the change should be made in the deployment.yaml for the field `containerPort` because the configmap.yaml has no explicit `listenPort` field.

```
 spec:
      hostNetwork: true
#     use label to selector node
      nodeName: fraporion00001
      containers:
      - name: edgemesh-server
        image: kubeedge/edgemesh-server:v1.7.0-21-ge18ebf1
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
        - containerPort: 10006
          name: relay
          protocol: TCP
        resources:
```

Maybe listenPort should be added with the default value to the configmap.yaml.
