### ISSUE TITLE
边缘端无法访问云端Pod

### ISSUE THREAD

**Issue by pengbinbin1** [kubeedge/edgemesh#521]
**What happened**:
边缘端无法访问位于云端的Pod，在边缘端发起dns请求，edgemesh-agent内日志可以看到请求目的地址转换为位于云端的corednsPod IP，但是访问这个PodIP出现超时，试了在边缘端宿主机和边缘端的Pod内访问位于云端的其他Pod，同样是访问超时。用的edgemesh是1.13.日志文件如下，有没有大佬可以帮忙看看，谢谢。

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by pengbinbin1** [comment]
[
[Uploading edgemesh-agent.log…]()
](url)

**Comment by Poorunga** [comment]
看一下你edgemesh-agent的配置

**Comment by pengbinbin1** [comment]
> 看一下你edgemesh-agent的配置

![Uploading 微信图片_20231121150434.jpg…]()

**Comment by pengbinbin1** [comment]
> 无法查看图片。不过可能你配置了forward，即会把dns请求发到云上的coredns service，这时候你要确保部署了coredns pod的节点有edgemesh-agent，流量才能代理过去

![Uploading 微信图片_20231121150434.jpg…]()

**Comment by Poorunga** [comment]
```
  edgeDNS:
    enable: true
    listenPort: 53
    cacheDNS:
      enable: false
      autoDetect: true
      upstreamServers:
      - 10.96.0.10
      - 1.1.1.1
      cacheTTL: 30
```

如上，cacheDNS启用的话，就会把流量往云上coredns转。不启用就只会访问边缘的dns
