### ISSUE TITLE
The default ports of edgemesh-server and edgeStream conflict

### ISSUE THREAD

**Issue by lynxcat** [kubeedge/edgemesh#79]
The The default ports of edgemesh-server and edgeStream conflict.

Environment:
- EdgeMesh version:1.8.0
- Kubernetes version (use `kubectl version`):1.20.4
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.6.2  

```
edgemesh-server.yaml  

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-server
  name: edgemesh-server
  namespace: kubeedge
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: edgemesh-server
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: edgemesh-server
    spec:
      hostNetwork: true
#     use label to selector node
      nodeName: marsone-cloud
      containers:
      - name: edgemesh-server
        image: kubeedge/edgemesh-server:latest
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
        - containerPort: 10004
---
cloudcore 

apiVersion: cloudcore.config.kubeedge.io/v1alpha2
    kind: CloudCore
    kubeAPIConfig:
      kubeConfig: ""
      master: ""
    modules:
      cloudHub:
        advertiseAddress:
        - 159.75.202.72
        nodeLimit: 100
        tlsCAFile: /etc/kubeedge/ca/rootCA.crt
        tlsCertFile: /etc/kubeedge/certs/edge.crt
        tlsPrivateKeyFile: /etc/kubeedge/certs/edge.key
        unixsocket:
          address: unix:///var/lib/kubeedge/kubeedge.sock
          enable: true
        websocket:
          address: 0.0.0.0
          enable: true
          port: 10000
        quic:
          address: 0.0.0.0
          enable: false
          maxIncomingStreams: 10000
          port: 10001
        https:
          address: 0.0.0.0
          enable: true
          port: 10002
      cloudStream:
        enable: true
        streamPort: 10003
        tunnelPort: 10004
      dynamicController:
        enable: true
```

**Comment by ZBoIsHere** [comment]
Yes, the default port value of edge Stream and edgemesh-server should be different. we will fix it soon.
you can modify the config of edgeStream or edgemesh-server. In edgeStream, the port value is defined in file "/etc/kubeedge/config/cloudcore.yaml", In edgemesh-server, the value is defined in configmap "edgemesh-server" in kubeedge namespace.

**Comment by lynxcat** [comment]
thanks.  
if i modify the config of edgemesh-server.  do i need to change anything else ?

**Comment by lynxcat** [comment]
edge-agent can't modify the port that connect to edgemesh-server.

```

edgemesh-server.yaml

  containers:
    - name: edgemesh-server
      image: 'kubeedge/edgemesh-server:latest'
      ports:
        - name: relay
          hostPort: 10005
          containerPort: 10005
          protocol: TCP
```
![917b7dc3a6904e99e12a6977a75b94c](https://user-images.githubusercontent.com/2222701/134279956-c6c6374a-db87-492a-98b6-364c526bff1e.png)

**Comment by Poorunga** [comment]
@lynxcat 

Have you changed the configuration of 05-configmap?

https://github.com/kubeedge/edgemesh/blob/main/build/server/edgemesh/05-configmap.yaml:
```
    modules:
      tunnel:
        enable: true
        publicIP: "127.0.0.1"
        listenPort: 10005       <-------------------------- here!!!
```
